//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    
    public partial class BoardTile
    {
        public int Width { get; set; }
        public int Height { get; set; }
        public int ColorId { get; set; }
        public int TypeId { get; set; }
        public Guid GameId { get; set; }
    
        public virtual PawnColor PawnColor { get; set; }
        public virtual GameManagment GameManagment { get; set; }
        public virtual PawnType PawnType { get; set; }
    }
}
